deployment:
  tasks:
  - export DEPLOYPATH=/home/j2mpnigpwwwi/public_html
  - /bin/cp index.html $DEPLOYPATH
  - /bin/cp blog.html $DEPLOYPATH 
  - /bin/cp header.js $DEPLOYPATH
  - /bin/cp app.css $DEPLOYPATH
  - /bin/cp scalevideo.js $DEPLOYPATH
  - /bin/cp -R images $DEPLOYPATH
  - /bin/cp -R biopages $DEPLOYPATH
  - /bin/cp cirrius.css $DEPLOYPATH
  
  