deployment:
  tasks:
  - export DEPLOYPATH=/home/j2mpnigpwwwi/public_html
  - /bin/cp index.html $DEPLOYPATH
  - /bin/cp header.js $DEPLOYPATH
  - /bin/cp app.css $DEPLOYPATH
  - /bin/cp -R images $DEPLOYPATH
  - /bin/cp -R biopages $DEPLOYPATH
  